[tools]
pinact = "latest"
node = "lts"
ghq = "latest"
fzf = "latest"
claude = "latest"
gemini = "latest"
"npm:@github/copilot" = "latest"
"npm:@openai/codex" = "latest"
"npm:prh" = "latest"
"npm:prh-languageserver" = "latest"
uv = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
experimental = true
