[tools]
claude = "latest"
fzf = "latest"
ghq = "latest"
node = "lts"
"npm:@openai/codex" = "latest"
"npm:prh" = "latest"
"npm:prh-languageserver" = "latest"
pinact = "latest"
pnpm = "latest"
uv = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
experimental = true
