[tools]
"aqua:k1LoW/mo" = "latest"
aws-cli = { version = "latest", symlink_bins = "true" }
bitwarden = "latest"
bitwarden-secrets-manager = "latest"
claude = "latest"
crane = "latest"
fzf = "latest"
gh = "latest"
ghq = "latest"
gitleaks = "latest"
herdr = "latest"
node = "lts"
"npm:@openai/codex" = "latest"
"npm:ccusage" = "latest"
"npm:pnpm" = "latest"
"npm:prh" = "latest"
"npm:prh-languageserver" = { version = "1.0.1", allow_low_downloads = true }
pinact = "latest"
prek = "latest"
uv = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
experimental = true
